# Generated by Django 2.0.4 on 2018-04-20 10:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wikidata_access_token',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='wikidata_access_token_created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
