# Generated by Django 2.0.4 on 2018-05-05 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('pid', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('template', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VendorGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=250)),
                ('qid', models.CharField(blank=True, max_length=50, null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='genre', to='vendor_data.Vendor')),
            ],
        ),
        migrations.CreateModel(
            name='VendorItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('status', models.PositiveIntegerField(choices=[(1, 'new'), (5, 'Pending creation of a new Wikidata ID'), (10, 'assigned'), (999, 'N/A (should not hava a wikidata ID)')], default=1)),
                ('vid', models.CharField(max_length=400, verbose_name='vendor_id')),
                ('type', models.IntegerField(choices=[(1, 'movie'), (2, 'person')])),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='year')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='duration')),
                ('title_he', models.CharField(blank=True, max_length=300, null=True, verbose_name='Hebrew title')),
                ('title_en', models.CharField(blank=True, max_length=300, null=True, verbose_name='English title')),
                ('summary_he', models.TextField(blank=True, null=True, verbose_name='summary in Hebrew')),
                ('summary_en', models.TextField(blank=True, null=True, verbose_name='summary in English')),
                ('editing_comment', models.TextField(blank=True, null=True, verbose_name='editing comment')),
                ('imdb_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='imdb ID')),
                ('content_type', models.ForeignKey(blank=True, limit_choices_to=models.Q(model__in=('person', 'movie')), null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType')),
                ('genre', models.ManyToManyField(blank=True, related_name='items', to='vendor_data.VendorGenre')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='vendor_data.Vendor')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='vendoritem',
            unique_together={('vendor', 'vid')},
        ),
        migrations.AlterUniqueTogether(
            name='vendorgenre',
            unique_together={('vendor', 'value')},
        ),
    ]
