# Generated by Django 2.0.4 on 2018-05-05 20:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendoritem',
            name='extra_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
