# Generated by Django 2.0.4 on 2018-05-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_data', '0002_vendoritem_extra_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendoritem',
            name='wikidata_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vendoritem',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'New'), (5, 'Pending creation of a new Wikidata ID'), (10, 'Assigned'), (999, 'N/A')], default=1),
        ),
    ]
