# Generated by Django 2.0.2 on 2018-02-23 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionmovie',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movies', to='curation.Collection'),
        ),
        migrations.AlterField(
            model_name='collectionmovie',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collections', to='movies.Movie'),
        ),
    ]
