# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-18 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieRolePerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='movies.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.IntegerField(unique=True)),
                ('name_he', models.CharField(blank=True, max_length=300, null=True)),
                ('name_en', models.CharField(blank=True, max_length=300, null=True)),
                ('first_name_he', models.CharField(blank=True, max_length=300, null=True)),
                ('first_name_en', models.CharField(blank=True, max_length=300, null=True)),
                ('last_name_he', models.CharField(blank=True, max_length=300, null=True)),
                ('last_name_en', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'person',
                'verbose_name_plural': 'people',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.CharField(max_length=300, unique=True)),
                ('title_en', models.CharField(blank=True, max_length=300, null=True)),
                ('title_he', models.CharField(blank=True, max_length=300, null=True)),
                ('appears_in_short_version', models.BooleanField(default=False)),
                ('short_version_order', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='movieroleperson',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='people.Person'),
        ),
        migrations.AddField(
            model_name='movieroleperson',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_people', to='people.Role'),
        ),
    ]
