# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-23 06:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieRolePerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('note', models.CharField(blank=True, max_length=250, null=True)),
                ('idea_uid', models.IntegerField(blank=True, null=True, unique=True)),
                ('idea_modified', models.BooleanField(default=False)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='movies.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('wikidata_status', models.PositiveIntegerField(blank=True, choices=[(10, 'assigned'), (50, 'Pending creation of a new Wikidata ID'), (999, 'N/A (should not hava a wikidata ID)')], null=True)),
                ('wikidata_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('name_he', models.CharField(blank=True, db_index=True, max_length=300, null=True)),
                ('name_en', models.CharField(blank=True, db_index=True, max_length=300, null=True)),
                ('first_name_he', models.CharField(blank=True, db_index=True, max_length=300, null=True)),
                ('first_name_en', models.CharField(blank=True, db_index=True, max_length=300, null=True)),
                ('last_name_he', models.CharField(blank=True, db_index=True, max_length=300, null=True)),
                ('last_name_en', models.CharField(blank=True, db_index=True, max_length=300, null=True)),
                ('idea_tid', models.IntegerField(blank=True, null=True, unique=True)),
                ('idea_modified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'person',
                'verbose_name_plural': 'people',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('wikidata_status', models.PositiveIntegerField(blank=True, choices=[(10, 'assigned'), (50, 'Pending creation of a new Wikidata ID'), (999, 'N/A (should not hava a wikidata ID)')], null=True)),
                ('wikidata_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('title_en', models.CharField(blank=True, max_length=300, null=True)),
                ('title_he', models.CharField(blank=True, max_length=300, null=True)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('appears_in_short_version', models.BooleanField(default=False)),
                ('short_version_order', models.PositiveIntegerField(blank=True, null=True)),
                ('idea_tid', models.CharField(blank=True, max_length=300, null=True, unique=True)),
                ('idea_modified', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='movieroleperson',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='people.Person'),
        ),
        migrations.AddField(
            model_name='movieroleperson',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_people', to='people.Role'),
        ),
        migrations.AlterUniqueTogether(
            name='movieroleperson',
            unique_together=set([('movie', 'role', 'person')]),
        ),
    ]
