# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-12 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='appears_in_short_version',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='short_version_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
