# Generated by Django 2.0.2 on 2018-02-23 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieroleperson',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='people', to='movies.Movie'),
        ),
        migrations.AlterField(
            model_name='movieroleperson',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movies', to='people.Person'),
        ),
        migrations.AlterField(
            model_name='movieroleperson',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movie_people', to='people.Role'),
        ),
    ]
