# Generated by Django 2.0.2 on 2018-02-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20180223_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieroleperson',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='person',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='role',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
    ]
