# Generated by Django 2.0.4 on 2018-04-21 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20180421_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='merged_into',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='people.Person'),
        ),
    ]
