# Generated by Django 2.0.4 on 2018-05-05 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_person_merged_into'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'role', 'verbose_name_plural': 'roles'},
        ),
    ]
