# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-22 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrich', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='status',
            field=models.IntegerField(choices=[(1, 'pending'), (5, 'error'), (10, 'no results'), (11, 'too many results'), (100, 'found (unverified)'), (200, 'verified'), (500, 'rejected')]),
        ),
    ]
