# Generated by Django 2.0.2 on 2018-02-26 22:58

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.query_utils


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('links', '0003_auto_20180224_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('object_id', models.PositiveIntegerField()),
                ('value', models.CharField(max_length=400, verbose_name='value or URL')),
                ('title_he', models.CharField(blank=True, max_length=300, null=True, verbose_name='Hebrew title')),
                ('title_en', models.CharField(blank=True, max_length=300, null=True, verbose_name='English title')),
                ('notes_he', models.TextField(blank=True, null=True, verbose_name='notes in Hebrew')),
                ('notes_en', models.TextField(blank=True, null=True, verbose_name='notes in English')),
                ('language', models.IntegerField(blank=True, choices=[(1, 'Hebrew'), (2, 'English')], null=True, verbose_name='language')),
                ('limit_to_language', models.BooleanField(default=False, verbose_name='limit to this language')),
                ('editing_comment', models.TextField(blank=True, null=True, verbose_name='editing comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('content_type', models.ForeignKey(limit_choices_to=django.db.models.query_utils.Q(model__in=('person', 'movie')), on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='links', to='links.LinkType', verbose_name='type')),
            ],
            options={
                'ordering': ('type__priority', '-created_at'),
            },
        ),
    ]
