# Generated by Django 2.0.2 on 2018-02-23 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editing_logs', '0002_logitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logitem',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
