# Generated by Django 2.0.2 on 2018-02-23 13:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editing_logs', '0003_auto_20180223_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='logitemrow',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None),
            preserve_default=False,
        ),
    ]
