# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-23 06:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('wikidata_status', models.PositiveIntegerField(blank=True, choices=[(10, 'assigned'), (50, 'Pending creation of a new Wikidata ID'), (999, 'N/A (should not hava a wikidata ID)')], null=True)),
                ('wikidata_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('title_en', models.CharField(max_length=300, verbose_name='Hebrew title')),
                ('title_he', models.CharField(max_length=300, verbose_name='English title')),
                ('appears_in_short_version', models.BooleanField(default=False, verbose_name='appears in short version')),
                ('short_version_order', models.PositiveIntegerField(blank=True, null=True, verbose_name='short version order')),
                ('idea_fid', models.CharField(max_length=300, unique=True)),
                ('idea_modified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'field',
                'verbose_name_plural': 'fields',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('wikidata_status', models.PositiveIntegerField(blank=True, choices=[(10, 'assigned'), (50, 'Pending creation of a new Wikidata ID'), (999, 'N/A (should not hava a wikidata ID)')], null=True)),
                ('wikidata_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('title_he', models.CharField(blank=True, max_length=300, null=True)),
                ('title_en', models.CharField(blank=True, max_length=300, null=True)),
                ('summary_he', models.TextField(blank=True, null=True)),
                ('summary_en', models.TextField(blank=True, null=True)),
                ('idea_bid', models.IntegerField(blank=True, null=True, unique=True)),
                ('idea_modified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'movie',
                'verbose_name_plural': 'movies',
            },
        ),
        migrations.CreateModel(
            name='MovieTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('idea_uid', models.IntegerField(blank=True, null=True, unique=True)),
                ('idea_modified', models.BooleanField(default=False)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='movies.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('wikidata_status', models.PositiveIntegerField(blank=True, choices=[(10, 'assigned'), (50, 'Pending creation of a new Wikidata ID'), (999, 'N/A (should not hava a wikidata ID)')], null=True)),
                ('wikidata_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('title_en', models.CharField(blank=True, max_length=300, null=True)),
                ('title_he', models.CharField(blank=True, max_length=300, null=True)),
                ('type_id', models.CharField(blank=True, max_length=300, null=True)),
                ('lang', models.CharField(blank=True, max_length=300, null=True)),
                ('idea_tid', models.IntegerField(blank=True, null=True, unique=True)),
                ('idea_modified', models.BooleanField(default=False)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='movies.Field')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='movietag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='movies.Tag'),
        ),
        migrations.AlterUniqueTogether(
            name='movietag',
            unique_together=set([('movie', 'tag')]),
        ),
    ]
