# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='bid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
