# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-07 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='title_en',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='title_he',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
