# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-07 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_tag_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag_field',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
