# Generated by Django 2.0.2 on 2018-04-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20180224_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='duration'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='summary_en',
            field=models.TextField(blank=True, null=True, verbose_name='English summary'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='summary_he',
            field=models.TextField(blank=True, null=True, verbose_name='Hebrew summary'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='English title'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title_he',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Hebrew title'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='year'),
        ),
    ]
