# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-07 15:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movie_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie_field',
            name='field',
        ),
        migrations.RemoveField(
            model_name='movie_field',
            name='movie',
        ),
        migrations.DeleteModel(
            name='Movie_Field',
        ),
    ]
