# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-07 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20180107_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_title',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
