# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 15:40
from __future__ import unicode_literals

from django.db import migrations


def switch_lang(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Description = apps.get_model('movies', 'Description')
    for description in Description.objects.all():
        description.lang = 'he' if description.lang == 'HEB' else 'en'
        description.save()


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20180107_1744'),
    ]

    operations = [
        migrations.RunPython(switch_lang),
    ]
