# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_auto_20180110_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='type_1',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
