# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-14 08:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_tag_type_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoviePerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie')),
                ('people', models.ManyToManyField(to='movies.Person')),
            ],
        ),
    ]
