# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-14 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_movieperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='tid',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
