# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-14 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_person_tid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='lang',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
