# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-15 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_auto_20180114_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag_field',
            name='field',
        ),
        migrations.RemoveField(
            model_name='tag_field',
            name='tag',
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name_en',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name_he',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name_en',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name_he',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='name_en',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='name_he',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='tid',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Tag_Field',
        ),
    ]
