# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-23 21:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0017_auto_20180115_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_Role_Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='movies.Movie')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='movies.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.CharField(max_length=300, unique=True)),
                ('title_en', models.CharField(blank=True, max_length=300, null=True)),
                ('title_he', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='movieperson',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='movieperson',
            name='people',
        ),
        migrations.DeleteModel(
            name='MoviePerson',
        ),
        migrations.AddField(
            model_name='movie_role_person',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_people', to='movies.Role'),
        ),
    ]
