# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-31 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0018_auto_20180123_2115'),
    ]

    operations = [
        migrations.RenameModel('Movie_Tag_Field', 'MovieTagField'),
        migrations.RenameModel('Collection_Movie', 'CollectionMovie'),
        migrations.RenameModel('Movie_Role_Person', 'MovieRolePerson'),
    ]
